language: node_js
node_js:
  - "6"
scala:
   - 2.10.4
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
after_install:
  - npm install -g .
  - npm install -g aglio
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
